'use client'
import { useCallback,useEffect,useState } from 'react'
import { useRouter } from 'next/navigation'
import { Save,WalletCards } from 'lucide-react'
import { Button } from '@/components/ui/button'
import { Card,CardContent,CardHeader,CardTitle } from '@/components/ui/card'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { fetchAdmin } from '@/lib/admin-fetch'

type ProviderState={providerKey:string;baseUrl:string;model:string;rateLimitedUntil:string|null;lastError:string|null;updatedAt:string}
type Payer={payerType:'reader'|'author';payerId:string;label:string;enabled:boolean;dailyBudgetUsd:number|null;monthlyBudgetUsd:number|null;maxBatchBudgetUsd:number|null;maxConcurrent:number;spentTodayUsd:number;spentMonthUsd:number;running:number}
const val=(v:number|null)=>v==null?'':String(v)
export default function BillingPage(){const router=useRouter();const adminFetch=useCallback((i:RequestInfo|URL,o:RequestInit={})=>fetchAdmin(i,router,o),[router]);const[payers,setPayers]=useState<Payer[]>([]);const[providers,setProviders]=useState<ProviderState[]>([]);const[busy,setBusy]=useState('');
 const load=useCallback(async()=>{const r=await adminFetch('/api/admin/llm-billing');if(r?.ok){const d=await r.json();setPayers(d.payers||[]);setProviders(d.providers||[])}},[adminFetch]);useEffect(()=>{const initial=setTimeout(()=>void load(),0);return()=>clearTimeout(initial)},[load]);
 const patch=(id:string,key:keyof Payer,value:any)=>setPayers(xs=>xs.map(x=>x.payerId===id?{...x,[key]:value}:x));
 async function save(p:Payer){setBusy(p.payerId);await adminFetch('/api/admin/llm-billing',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(p)});await load();setBusy('')}
 return <div className="mx-auto max-w-6xl space-y-6 p-4 md:p-6 lg:p-8"><div><h1 className="text-2xl font-bold">LLM бюджеты</h1><p className="text-sm text-muted-foreground">Reader и каждый псевдоним могут иметь отдельный бюджет и concurrency.</p></div>{providers.length>0&&<Card><CardHeader><CardTitle className="text-base">Provider rate-limit</CardTitle></CardHeader><CardContent className="space-y-2 text-sm">{providers.map(p=><div key={p.providerKey} className="flex flex-wrap justify-between gap-2 border-b pb-2"><span>{p.model}</span><span className={p.rateLimitedUntil&&new Date(p.rateLimitedUntil)>new Date()?'text-amber-700':'text-muted-foreground'}>{p.rateLimitedUntil&&new Date(p.rateLimitedUntil)>new Date()?`cooldown до ${new Date(p.rateLimitedUntil).toLocaleTimeString('ru-RU')}`:'готов'}</span></div>)}</CardContent></Card>}<div className="grid gap-4 lg:grid-cols-2">{payers.map(p=><Card key={`${p.payerType}:${p.payerId}`}><CardHeader><CardTitle className="flex items-center gap-2 text-base"><WalletCards className="h-4 w-4"/>{p.payerType==='author'?'Автор':'Reader'}: {p.label}</CardTitle></CardHeader><CardContent className="space-y-4"><div className="grid grid-cols-2 gap-3 text-sm"><div>Сегодня: <b>${p.spentTodayUsd.toFixed(5)}</b></div><div>Месяц: <b>${p.spentMonthUsd.toFixed(5)}</b></div><div>Running: <b>{p.running}/{p.maxConcurrent}</b></div></div><div className="grid gap-3 sm:grid-cols-2"><div><Label>День, USD</Label><Input type="number" min="0" step="0.01" value={val(p.dailyBudgetUsd)} onChange={e=>patch(p.payerId,'dailyBudgetUsd',e.target.value===''?null:Number(e.target.value))}/></div><div><Label>Месяц, USD</Label><Input type="number" min="0" step="0.01" value={val(p.monthlyBudgetUsd)} onChange={e=>patch(p.payerId,'monthlyBudgetUsd',e.target.value===''?null:Number(e.target.value))}/></div><div><Label>Max batch, USD</Label><Input type="number" min="0" step="0.01" value={val(p.maxBatchBudgetUsd)} onChange={e=>patch(p.payerId,'maxBatchBudgetUsd',e.target.value===''?null:Number(e.target.value))}/></div><div><Label>Concurrency</Label><Input type="number" min="1" max="32" value={p.maxConcurrent} onChange={e=>patch(p.payerId,'maxConcurrent',Number(e.target.value)||1)}/></div></div><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={p.enabled} onChange={e=>patch(p.payerId,'enabled',e.target.checked)}/>Разрешить расходы</label><Button onClick={()=>void save(p)} disabled={busy===p.payerId}><Save className="mr-2 h-4 w-4"/>{busy===p.payerId?'Сохраняем…':'Сохранить'}</Button></CardContent></Card>)}</div></div>}
