'use client'
import { useCallback,useEffect,useMemo,useState } from 'react'
import { useRouter } from 'next/navigation'
import { Pause,Play,RotateCcw,XCircle,RefreshCw,Layers3 } from 'lucide-react'
import { Button } from '@/components/ui/button'
import { Card,CardContent,CardHeader,CardTitle } from '@/components/ui/card'
import { Badge } from '@/components/ui/badge'
import { Progress } from '@/components/ui/progress'
import { fetchAdmin } from '@/lib/admin-fetch'

type Batch={id:string;title:string;kind:string;status:string;totalJobs:number;completedJobs:number;counts:Record<string,number>;actualCostUsd:number;estimatedCostUsd:number;totalTokens:number;createdAt:string;completedAt:string|null;payerType:string;payerId:string|null;payerLabel:string;pauseReason:string|null;etaSeconds:number|null;avgJobSeconds:number|null;author:{name:string;slug:string}|null;book:{title:string;slug:string}|null}
const money=(v:number)=>v<.01?`$${v.toFixed(5)}`:`$${v.toFixed(3)}`
const labels:Record<string,string>={running:'Выполняется',paused:'Пауза',completed:'Завершено',cancelled:'Отменено','paused-budget':'Бюджет',preparing:'Подготовка'}
export default function LlmBatchesPage(){const[data,setData]=useState<Batch[]>([]);const[loading,setLoading]=useState(true);const router=useRouter();const adminFetch=useCallback((input:RequestInfo|URL,options:RequestInit={})=>fetchAdmin(input,router,options),[router])
 const load=useCallback(async()=>{const r=await adminFetch('/api/admin/llm-batches');if(r?.ok)setData((await r.json()).batches||[]);setLoading(false)},[adminFetch])
 useEffect(()=>{const initial=setTimeout(()=>void load(),0);const t=setInterval(()=>void load(),3000);return()=>{clearTimeout(initial);clearInterval(t)}},[load])
 async function act(id:string,action:string){await adminFetch(`/api/admin/llm-batches/${id}/action`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action})});await load()}
 const active=useMemo(()=>data.filter(x=>x.status==='running').length,[data])
 return <div className="mx-auto max-w-6xl space-y-6 p-4 md:p-6 lg:p-8"><div className="flex items-center justify-between gap-3"><div><h1 className="text-2xl font-bold">Длинные задачи</h1><p className="text-sm text-muted-foreground">Batch-задачи живут независимо от браузера. Активных: {active}</p></div><Button variant="outline" onClick={()=>void load()}><RefreshCw className="mr-2 h-4 w-4"/>Обновить</Button></div>
 {loading?<div className="text-muted-foreground">Загрузка…</div>:data.length===0?<Card><CardContent className="p-10 text-center text-muted-foreground"><Layers3 className="mx-auto mb-3 h-8 w-8"/>Длинных задач пока нет. «Генерировать для всех глав» создаст первую.</CardContent></Card>:<div className="space-y-4">{data.map(b=>{const pct=b.totalJobs?Math.round(b.completedJobs/b.totalJobs*100):100;return <Card key={b.id}><CardHeader className="pb-3"><div className="flex flex-wrap items-start justify-between gap-3"><div><CardTitle className="text-base">{b.title}</CardTitle><div className="mt-1 text-xs text-muted-foreground">{b.author?.name||'Все псевдонимы'} · {b.book?.title||'Все книги'} · платит {b.payerType==='author'?'автор':'Reader'}: {b.payerLabel} · {new Date(b.createdAt).toLocaleString('ru-RU')}</div></div><Badge variant="outline">{labels[b.status]||b.status}</Badge></div></CardHeader><CardContent className="space-y-4"><div><div className="mb-1 flex justify-between text-xs"><span>{b.completedJobs} / {b.totalJobs}</span><span>{pct}%</span></div><Progress value={pct}/></div><div className="grid gap-3 sm:grid-cols-4"><div><div className="text-xs text-muted-foreground">Готово</div><div className="font-semibold">{b.counts.succeeded||0}</div></div><div><div className="text-xs text-muted-foreground">Ошибки</div><div className="font-semibold">{b.counts.failed||0}</div></div><div><div className="text-xs text-muted-foreground">Токены</div><div className="font-semibold">{b.totalTokens.toLocaleString('ru-RU')}</div>{b.etaSeconds!=null&&b.status==='running'&&<div className="text-[10px] text-muted-foreground">ETA ≈ {Math.ceil(b.etaSeconds/60)} мин.</div>}</div><div><div className="text-xs text-muted-foreground">Стоимость</div><div className="font-semibold">{money(b.actualCostUsd)}</div><div className="text-[10px] text-muted-foreground">estimate {money(b.estimatedCostUsd)}</div></div></div>{b.pauseReason&&<div className="text-sm text-amber-700">{b.pauseReason}</div>}<div className="flex flex-wrap gap-2">{b.status==='running'&&<Button size="sm" variant="outline" onClick={()=>void act(b.id,'pause')}><Pause className="mr-1 h-4 w-4"/>Пауза</Button>}{['paused','paused-budget'].includes(b.status)&&<Button size="sm" variant="outline" onClick={()=>void act(b.id,'resume')}><Play className="mr-1 h-4 w-4"/>Продолжить</Button>}{(b.counts.failed||0)>0&&<Button size="sm" variant="outline" onClick={()=>void act(b.id,'retry-failed')}><RotateCcw className="mr-1 h-4 w-4"/>Повторить ошибки</Button>}{['running','paused','paused-budget'].includes(b.status)&&<Button size="sm" variant="ghost" className="text-destructive" onClick={()=>void act(b.id,'cancel')}><XCircle className="mr-1 h-4 w-4"/>Отменить</Button>}</div></CardContent></Card>})}</div>}</div>}
